version: '3.8'

services:
  neo4j:
    image: neo4j:5.24
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - TZ=Asia/Tehran
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
      
  redis:
    image: redis
    expose:
      - 6379
    ports: 
      - 6379:6379
    environment:
      - TZ=Asia/Tehran

volumes:
  app-logs:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
